django_user/config/urls.py
from django.contrib import admin
from django.urls import path, include
from user import views

urlpatterns = [
    path("admin/", admin.site.urls),

    # http://127.0.0.1:8000/
    path('', views.index, name="index"),

    # http://127.0.0.1:8000/user/
    path("user/", include('user.urls')),

    # http://127.0.0.1:8000/accounts/
    # path("accounts/", include('django.contrib.auth.urls')),
]

django_user/user/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

app_name = "user"

urlpatterns = [
    # http://127.0.0.1:8000/user
    path('', views.index, name="index"),

    # http://127.0.0.1:8000/user/signup/
    path('signup/', views.signup, name="signup"),

    # http://127.0.0.1:8000/user/login/
    # path('login/', views.custom_login, name="login"),

    # http://127.0.0.1:8000/user/logout/
    # path('logout/', views.custom_logout, name="logout"),


    # 장고의 auth.urls 이용을 하되 필요한 부분만 연결하기
    # http://127.0.0.1:8000/user/login/
    # template_name 을 지정하지 않으면 registration/login.html 로 감
    path('login/', auth_views.LoginView.as_view(template_name="user/login.html"), name="login"),

    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    # http://127.0.0.1:8000/user/password_change/
    # 비밀번호 변경 성공하는 경우 path("password_change/done/", user/password_change/done/ name="password_change_done" url 필요함
    # path("password_change/",auth_views.PasswordChangeView.as_view(template_name="user/password_change.html"), name="password_change"),
    path("password_change/",views.CustomPassWordChangeView.as_view(template_name="user/password_change.html"), name="password_change"),
]

django_user/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ['username', 'email']

django_user/user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy

from .forms import UserForm

def index(request):
    return render(request,"index.html")

def signup(request):
    """
    회원가입
    """

    if request.method == "POST":
        # post로 넘어오는 값에 대해 UserForm 바인딩 처리
        form = UserForm(request.POST)
       
        # 폼 검증 
        if form.is_valid():
            #저장
            form.save()
            return redirect("user:login")
    else:
        form = UserForm()

    return render(request, "user/signup.html",{"form":form})

# def custom_login(request):
#     """
#     커스텀 로그인 - 직접 구현
#     """
#     if request.method == "POST":
#         # 아이디(사용자이름)와 비밀번호 가져오기
#         username = request.POST['username']
#         password = request.POST['password']

#         # 인증(로그인 값이 정확한가?)
#         user = authenticate(request,username=username,password=password)

#         # 정확하면 세션에 값을 담게 됨
#         if user is not None:
#             login(request, user)
#             return redirect("user:index")
        
#     return render(request,"user/login.html")

# def custom_logout(request):
#     """
#     커스텀 로그아웃 - 직접 구현
#     """
#     # 세션 해제
#     logout(request)
#     return redirect("index")


#################################
# 장고 회원 URL 이용하기
#################################

class CustomPassWordChangeView(PasswordChangeView):
    success_url = reverse_lazy("user:index")

django_user/templates/user/login.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <div class="row my-3">
      <div class="col-4">
        <h4>로그인</h4>
      </div>
      <div class="col-8 text-right">
        <span>또는</span>
        <a href="{% url 'user:signup' %}">계정 생성</a>
        <span>또는</span>
        <a href="{% url 'user:password_change' %}">비밀번호 변경</a>
      </div>
    </div>
  </div>
  <hr class="mt-1">
  <div class="content-block">
    {% include 'form_errors.html' %}
    <form method="post" class="post-form">
      {% csrf_token %}
      <div class="form-group">
        <label for="username">사용자 이름</label>
        <input type="text" name="username" id="username" class="form-control" value="{{form.username.value|default_if_none:''}}">
      </div>
      <div class="form-group">
        <label for="password">비밀번호</label>
        <input type="password" name="password" id="password" class="form-control" value="{{form.password1.value|default_if_none:''}}">
      </div>
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">로그인</button>
    </div>
  </form>
</div>
{% endblock content %}

django_user/templates/user/password_change.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <div class="row my-3">
      <div class="col-4">
        <h4>비밀번호 변경</h4>
      </div>
      <div class="col-8 text-right">
        <span>또는</span>
        <a href="{% url 'user:signup' %}">계정을 만드세요</a>
      </div>
    </div>
  </div>
  {% include "form_errors.html" %}
  <form method="post" class="post-form">
    {% csrf_token %}
    <div class="form-group">
      <label for="old_password">기존 비밀번호</label>
      <input type="password" name="old_password" id="old_password" class="form-control" value="{{form.old_password.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <label for="password1">새 비밀번호</label>
      <input type="password" name="new_password1" id="new_password1" class="form-control" value="{{form.new_password1.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <label for="password2">새 비밀번호 확인</label>
      <input type="password" name="new_password2" id="new_password2" class="form-control" value="{{form.new_password2.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">비밀번호 변경</button>
    </div>
  </form>
{% endblock content %}

django_user/templates/user/signup.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <div class="row my-3">
      <div class="col-4">
        <h4>회원가입</h4>
      </div>
      <div class="col-8 text-right">
        <span>또는</span>
        <a href="{% url 'user:login' %}">로그인 하세요</a>
      </div>
    </div>
  </div>

  {% comment %} {{form.as_p}} {% endcomment %}
  {% include "form_errors.html" %}
  <form method="post" class="post-form">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">사용자 이름</label>
      <input type="text" name="username" id="username" class="form-control" value="{{form.username.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <label for="password1">비밀번호</label>
      <input type="password" name="password1" id="password1" class="form-control" value="{{form.password1.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <label for="password2">비밀번호 확인</label>
      <input type="password" name="password2" id="password2" class="form-control" value="{{form.password2.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <label for="email">이메일</label>
      <input type="text" name="email" id="email" class="form-control" value="{{form.email.value|default_if_none:''}}">
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">회원가입</button>
    </div>
  </form>
{% endblock content %}