myboard/board/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, voter_views

app_name = "board"

urlpatterns = [
    
    #### 질문

    # http://127.0.0.1:8000/board/
    path('',base_views.index, name="index"),

    # http://127.0.0.1:8000/board/1/
    path('<int:question_id>/',base_views.question_detail, name="question_detail"),
    
    # http://127.0.0.1:8000/board/question/create/
    path('question/create/',question_views.question_create, name="question_create"),

    # http://127.0.0.1:8000/board/question/modify/1/
    path('question/modify/<int:question_id>/',question_views.question_modify, name="question_modify"),
    
    # http://127.0.0.1:8000/board/question/delete/1/
    path('question/delete/<int:question_id>/',question_views.question_delete, name="question_delete"),


    ###### 답변 

    # http://127.0.0.1:8000/board/answer/create/1/
    path('answer/create/<int:question_id>/',answer_views.answer_create, name="answer_create"),

    # http://127.0.0.1:8000/board/answer/modify/1/
    path('answer/modify/<int:answer_id>/',answer_views.answer_modify, name="answer_modify"),

    # http://127.0.0.1:8000/board/answer/delete/1/
    path('answer/delete/<int:answer_id>/',answer_views.answer_delete, name="answer_delete"),


    #### Comment
    # http://127.0.0.1:8000/board/comment/create/question/1/
    path('comment/create/question/<int:question_id>/',comment_views.comment_create_question, name="comment_create_question"),


    # http://127.0.0.1:8000/board/comment/modify/question/1/
    path('comment/modify/question/<int:comment_id>/',comment_views.comment_modify_question, name="comment_modify_question"),

    # http://127.0.0.1:8000/board/comment/delete/question/1/
    path('comment/delete/question/<int:comment_id>/',comment_views.comment_delete_question, name="comment_delete_question"),
   
    path('comment/create/answer/<int:answer_id>/',comment_views.comment_create_answer, name="comment_create_answer"),
    path('comment/modify/answer/<int:comment_id>/',comment_views.comment_modify_answer, name="comment_modify_answer"),
    path('comment/delete/answer/<int:comment_id>/',comment_views.comment_delete_answer, name="comment_delete_answer"),



    #### 추천
    # http://127.0.0.1:8000/board/vote/question/1/
    path('vote/question/<int:question_id>/',voter_views.vote_question, name="vote_question"),
    path('vote/answer/<int:answer_id>/',voter_views.vote_answer, name="vote_answer"),
]

myboard/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views

from board.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/',include('board.urls')),
    path('users/',include('users.urls')),
    path('', base_views.index),

    # path("", include("django.contrib.auth.urls")),
    
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

myboard/board/models.py
from django.db import models
from django.contrib.auth.models import User

# 질문(Question) 모델
# 제목(subject-200), 내용(content), created_at()
class Question(models.Model):
    subject = models.CharField(max_length=200,verbose_name="제목")
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="작성자")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="작성날짜")
    # modified_at 컬럼 추가
    modified_at = models.DateTimeField(auto_now=True,verbose_name="수정날짜")
    # 추천
    voter = models.ManyToManyField(User, related_name='voter_question')
    # 조회수
    read_cnt = models.BigIntegerField(default=0)

    def __str__(self) -> str:
        return self.subject


class QuestionCount(models.Model):
    ip = models.CharField(max_length=30)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip





# 답변(Answer) 모델
# question(질문과 외래키), 내용(content), created_at
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="작성자")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="작성날짜")
    # modified_at 컬럼 추가
    modified_at = models.DateTimeField(auto_now=True,verbose_name="수정날짜")
    # 추천
    voter = models.ManyToManyField(User, related_name='voter_answer')



# 댓글 - 작성자, 댓글내용, 댓글작성일시, 댓글 수정일시, 이 댓글이 달린 질문, 이 댓글이 달린 답변
class Comment(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name="작성자")
    content = models.TextField(verbose_name="댓글 내용")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="작성날짜")  
    modified_at = models.DateTimeField(auto_now=True,verbose_name="수정날짜")
    question = models.ForeignKey(Question, on_delete=models.CASCADE,null=True, blank=True, verbose_name="질문")
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE,null=True, blank=True, verbose_name="답변")

myboard/board/forms.py
from django import forms

from .models import Answer, Comment, Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']


# AnsworForm - fields : content
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']


# CommentForm - fields : content
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

myboard/board/views/answer_views.py
from django.shortcuts import redirect, render,get_object_or_404,resolve_url
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from ..forms import AnswerForm, CommentForm, QuestionForm
from ..models import Answer, Question, Comment


@login_required(login_url='users:login')
def answer_create(request,question_id):
    """
    Answer 등록
    """
    question = get_object_or_404(Question,id=question_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            # 성공시 - 페이지의 맨 처음으로 되돌아가게 됨
            # return redirect("board:question_detail",question_id=question_id)

            # 사용자가 작성한 댓글의 위치로 돌려보내려면?
            # resolve_url : 실제 호출되는 url을 문자열로 반환하는 장고 함수
            return redirect("{}#answer_{}".format(resolve_url("board:question_detail",question_id=question_id),answer.id))
    else:
        form = AnswerForm()
        
    return render(request, "board/question_detail.html",{"form":form,"question":question})

@login_required(login_url='users:login')
def answer_modify(request,answer_id):

    answer = get_object_or_404(Answer, pk=answer_id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.save()
            # return redirect("board:question_detail", question_id = answer.question_id)
            return redirect("{}#answer_{}".format(resolve_url("board:question_detail",question_id=answer.question_id),answer.id))
    else:
        form = AnswerForm(instance=answer)
    return render(request, "board/answer_modify.html",{"form":form})

@login_required(login_url='users:login')
def answer_delete(request,answer_id):
    
    answer = get_object_or_404(Answer,pk=answer_id)

    answer.delete()
    # return redirect("board:index")
    return redirect("board:question_detail", question_id=answer.question_id)

myboard/board/views/base_views.py
from django.shortcuts import redirect, render,get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from tools.utils import get_client_ip

from ..forms import AnswerForm, CommentForm, QuestionForm
from ..models import Answer, Question, Comment, QuestionCount

from django.db.models import Q,Count

def index(request):
    """
    Question 질문목록 추출
    """

    # 사용자가 입력한 검색어 가져오기
    keyword = request.GET.get('keyword','')

    # 사용자가 요청한 페이지 값 가져오기
    page = request.GET.get("page", 1)

    # 사용자가 입력한 정렬기준 가져오기
    so = request.GET.get('so','recent')

    if so == "recommend":
        question_lists = Question.objects.annotate(num_voter = Count('voter')).order_by('-num_voter', '-created_at')
    elif so == "popular":
        question_lists = Question.objects.annotate(num_answer = Count('answer')).order_by('-num_answer', '-created_at')
    else:
        # 전체 목록 추출 - 최신순
        question_lists = Question.objects.order_by("-created_at")

    # 검색결과 리스트 추출
    # subject, content, author 항목들이 검색어와 일치하는 경우를 추출
    # Q : or 조건으로 데이터 조회
    # icontains : 대소문자 구별 없이
    if keyword:
        question_lists = question_lists.filter(
            Q(subject__icontains = keyword) |
            Q(content__icontains = keyword) |
            Q(author__username__icontains = keyword) 
        ).distinct()


    # 전체 목록 안에서 사용자가 요청한 페이지에 대한 목록만 전송
    paginator = Paginator(question_lists, 10)
    question_list = paginator.get_page(page)

    return render(request, "board/question_list.html",{"question_list":question_list,'page':page,'keyword':keyword,'so':so})


def question_detail(request,question_id):
    """
    Question 상세 내용 추출
    """
    question = get_object_or_404(Question, id=question_id)

    ip = get_client_ip(request)
    cnt = QuestionCount.objects.filter(ip=ip, question=question).count()

    if cnt == 0:
        qc = QuestionCount(ip=ip, question=question)
        qc.save()

        if question.read_cnt:
            question.read_cnt += 1
        else:
            question.read_cnt = 1
        question.save()




    # 사용자가 입력한 검색어 가져오기
    keyword = request.GET.get('keyword','')
    # 사용자가 요청한 페이지 값 가져오기
    page = request.GET.get("page", 1)
    # 사용자가 입력한 정렬기준 가져오기
    so = request.GET.get('so','recent')


    return render(request, "board/question_detail.html",{"question":question,'page':page,'keyword':keyword,'so':so})

myboard/board/views/comment_views.py
from django.shortcuts import redirect, render,get_object_or_404,resolve_url
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from ..forms import AnswerForm, CommentForm, QuestionForm
from ..models import Answer, Question, Comment

@login_required(login_url='users:login')
def comment_create_question(request,question_id):
    """
    질문 댓글 등록
    """

    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.question = question
            comment.save()
            # return redirect("board:question_detail",question_id=question_id)
            return redirect("{}#comment_{}".format(resolve_url("board:question_detail",question_id=question_id),comment.id))
    else:
        form = CommentForm()
    return render(request, "board/comment_create.html",{"form":form})

@login_required(login_url='users:login')
def comment_modify_question(request,comment_id):
    """
    질문 댓글 수정 => 템플릿은 comment_create 사용
    """
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.save()
            # return redirect("board:question_detail",question_id=comment.question.id)
            return redirect("{}#comment_{}".format(resolve_url("board:question_detail",question_id=comment.question.id),comment.id))

    else:
        form = CommentForm(instance=comment)
        
    return render(request, "board/comment_create.html",{"form":form})

@login_required(login_url='users:login')
def comment_delete_question(request,comment_id):
    """
    질문 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()

    return redirect("board:question_detail",question_id=comment.question.id)


@login_required(login_url='users:login')
def comment_create_answer(request, answer_id):
    """
    답변 댓글 등록
    """

    answer = get_object_or_404(Answer, pk=answer_id)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.answer = answer
            comment.save()
            # return redirect("board:question_detail",question_id=comment.answer.question.id)
            return redirect("{}#comment_{}".format(resolve_url("board:question_detail",question_id=comment.answer.question.id),comment.id))
    else:
        form = CommentForm()
    return render(request, "board/comment_create.html",{"form":form})

@login_required(login_url='users:login')
def comment_modify_answer(request,comment_id):
    """
    답변 댓글 수정 => 템플릿은 comment_create 사용
    """
    comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.save()
            # return redirect("board:question_detail",question_id=comment.answer.question.id)
            return redirect("{}#comment_{}".format(resolve_url("board:question_detail",question_id=comment.answer.question.id),comment.id))
    else:
        form = CommentForm(instance=comment)
        
    return render(request, "board/comment_create.html",{"form":form})

@login_required(login_url='users:login')
def comment_delete_answer(request,comment_id):
    """
    질문 댓글 삭제
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()

    return redirect("board:question_detail",question_id=comment.answer.question.id)

myboard/board/views/question_views.py
from django.shortcuts import redirect, render,get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from ..forms import AnswerForm, CommentForm, QuestionForm
from ..models import Answer, Question, Comment

@login_required(login_url='users:login')
def question_create(request):
    """
    Question 등록
    """
    if request.method == "POST":
        form = QuestionForm(request.POST)

        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()

            return redirect("board:index")
    else:
        form = QuestionForm()

    return render(request, "board/question_create.html",{"form":form})

@login_required(login_url='users:login')
def question_modify(request,question_id):
    """
    Question 수정
    """
    question = get_object_or_404(Question, pk=question_id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)

        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            # 성공시 detail 
            return redirect("board:question_detail",question_id=question_id)
    else:
        form = QuestionForm(instance=question)

    return render(request, "board/question_modify.html", {"form":form})

@login_required(login_url='users:login')
def question_delete(request, question_id):
    """
    Question 삭제
    """
    question = get_object_or_404(Question, pk=question_id)

    question.delete()
    # 성공시 list 보여주기
    return redirect("board:index")

myboard/board/views/voter_views.py
from django.shortcuts import redirect, render,get_object_or_404
from django.contrib.auth.decorators import login_required
from ..models import Answer, Question

from django.contrib import messages

@login_required(login_url='users:login')
def vote_question(request, question_id):
    """
    질문 추천 등록 : 본인이 작성한 글은 추천하지 못하도록 함/성공-detail
    """

    question = get_object_or_404(Question, pk=question_id)

    if question.author == request.user:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")
    else:
        question.voter.add(request.user)

    return redirect("board:question_detail", question_id=question_id)


@login_required(login_url='users:login')
def vote_answer(request, answer_id):
    """
    답변 추천 등록 : 본인이 작성한 글은 추천하지 못하도록 함/성공-detail
    """

    answer = get_object_or_404(Answer, pk=answer_id)

    if answer.author == request.user:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")
    else:
        answer.voter.add(request.user)

    return redirect("board:question_detail", question_id=answer.question.id)

myboard/templates/board/answer_modify.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <h5 class="border-bottom py-2">
      답변 수정
    </h5>
    {% include 'form_errors.html' %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">수정하기</button>
      </div>
    </form>
  </div>
{% endblock content %}

myboard/templates/board/board_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <h1>질문 목록</h1>
    <table class="table">
      <thead>
        <tr class="thead-dark">
          <th>번호</th>
          <th>제목</th>
          <th>작성일시</th>
        </tr>
      </thead>
      <tbody>
        <!--반복될 부분-->
        {% for question in question_list %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>
              <a href="">{{question.subject}}</a>
            </td>
            <td>{{question.created_at}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="" class="btn btn-primary">질문 등록</a>
  </div>
{% endblock content %}

myboard/templates/board/comment_create.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <h5 class="border-bottom py-2">
      질문 등록
    </h5>
    {% include 'form_errors.html' %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="content">댓글 내용</label>
        <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">댓글 저장</button>
      </div>
    </form>
  </div>
{% endblock content %}

myboard/templates/board/question_create.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <h5 class="border-bottom py-2">
      질문 등록
    </h5>
    {% include 'form_errors.html' %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="subject">제목</label>
        <input type="text" name="subject" id="subject" class="form-control" value="{{form.subject.value|default_if_none:''}}">
      </div>
      <div class="form-group">
        <label for="content">내용</label>
        <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">질문하기</button>
      </div>
    </form>
  </div>
{% endblock content %}

myboard/templates/board/question_detail.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
  <div class="container my-3">
    {% if messages %}
      <div class="alert alert-danger my-3">
        {% for msg in messages %}
          <strong>{{msg.tags}}</strong>
          <ul>
            <li>{{msg.message}}</li>
          </ul>
        {% endfor %}
      </div>
    {% endif %}
    <h2 class="border-bottom py-2">
      <!--질문 제목-->
      {{question.subject}}
    </h2>
    <div class="row my-3">
      <div class="col-1">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{question.voter.count}}</div>
        <a href="#" class="recommend btn btn-sm btn-secondary btn-block my-1" data-uri="{% url 'board:vote_question' question.id %}">추천</a>
      </div>
      <div class="col-11">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <!--질문 내용-->
              {{question.content|mark}}
            </div>
            <div class="d-flex justify-content-end">
              <div class="badge badge-light p-2 text-left">
                <!--작성자-->
                <div class="mb-2">{{question.author.username}}</div>
                <!--질문 작성날짜-->
                {{question.created_at}}
              </div>
            </div>
            <div class="d-flex justify-content-end">
              <div class="badge badge-light p-2 text-left">
                <div class="mb-2">수정날짜</div>
                <!--질문 수정날짜-->
                {{question.modified_at}}
              </div>
            </div>
            <!-- 로그인 사용자가 질문 작성자와 동일할 경우만 보여주기-->
            {% if request.user == question.author %}
              <div class="my-3">
                <a href="{% url 'board:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="btn btn-sm btn-outline-danger" data-uri="{% url 'board:question_delete' question.id %}">삭제</a>
              </div>
            {% endif %}
            <!-- 질문 comment 영역 -->
            {% if question.comment_set.count > 0 %}
              <div class="mt-3">
                {% for comment in question.comment_set.all %}
                  <a name="comment_{{comment.id}}"></a>
                  <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line">
                      <!--댓글 내용-->
                      {{comment.content}}
                    </span>
                    <span>
                      <!--댓글작성자, 댓글작성날짜-->
                      {{comment.author}},
                      {{comment.created_at}}
                      {% if comment.created_at < comment.modified_at %}
                        (수정:{{comment.modified_at}})
                      {% endif %}
                    </span>
                    <a href="{% url 'board:comment_modify_question' comment.id %}" class="small">수정</a>
                    <a href="#" class="small delete" data-uri="{% url 'board:comment_delete_question' comment.id %}">삭제</a>
                  </div>
                {% endfor %}
              </div>
            {% endif %}
            <div>
              <a href="{% url 'board:comment_create_question' question.id %}" class="small">댓글추가....</a>
            </div>
            <!--질문 comment 종료-->
          </div>
        </div>
      </div>
      <!--목록버튼-->
      <div class="row">
        <div class="col-1"></div>
        <div class="col-11">
          <form action="{% url 'board:index' %}" method="get" id="searchForm">
            <input type="hidden" name="keyword" value="{{keyword|default_if_none:''}}" id="keyword">
            <input type="hidden" name="page" value="{{page}}" id="page">
            <input type="hidden" name="so" value="{{so}}" id="so">
          </form>
          <div class="my-3">
            <a href="javascript:void(0);" class="btn btn-sm btn-outline-success">목록으로</a>
          </div>
        </div>
      </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
      <!--답변 개수 보여주기 -->
      {{question.answer_set.count}}개의 답변이 있습니다.
    </h5>
    <div class="col-11">
      <!-- 답변 반복될 부분-->
      {% for answer in question.answer_set.all %}
        <a name="answer_{{answer.id}}"></a>
        <div class="row my-3">
          <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
            <a href="#" class="recommend btn btn-sm btn-secondary btn-block my-1" data-uri="{% url 'board:vote_answer' answer.id %}">추천</a>
          </div>
          <div class="col-11">
            <div class="card">
              <div class="card-body">
                <div class="card-text">
                  <!--답변 내용-->
                  {{answer.content|mark}}
                </div>
                <div class="d-flex justify-content-end">
                  <div class="badge badge-light p-2 text-left">
                    <!--작성자-->
                    <div class="mb-2">{{answer.author.username}}</div>
                    <!--답변 작성날짜-->
                    {{answer.created_at}}
                  </div>
                </div>
                <div class="d-flex justify-content-end">
                  <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">수정일</div>
                    <!--답변 작성날짜-->
                    {{answer.modified_at}}
                  </div>
                </div>
                <!-- 답변 작성자와 로그인 사용자가 일치하면-->
                {% if request.user == answer.author %}
                  <div class="my-3">
                    <a href="{% url 'board:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="btn btn-sm btn-outline-danger" data-uri="{% url 'board:answer_delete' answer.id %}">삭제</a>
                  </div>
                {% endif %}
                <!-- 답변 comment 영역 -->
                {% if answer.comment_set.count > 0 %}
                  <div class="mt-3">
                    {% for comment in answer.comment_set.all %}
                      <a name="comment_{{comment.id}}"></a>
                      <div class="comment py-2 text-muted">
                        <span style="white-space: pre-line">
                          <!--댓글 내용-->
                          {{comment.content}}
                        </span>
                        <span>
                          <!--댓글작성자, 댓글작성날짜-->
                          {{comment.author}},
                          {{comment.created_at}}
                          {% if comment.created_at < comment.modified_at %}
                            (수정:{{comment.modified_at}})
                          {% endif %}
                        </span>
                        <a href="{% url 'board:comment_modify_answer' comment.id %}" class="small">수정</a>
                        <a href="#" class="small delete" data-uri="{% url 'board:comment_delete_answer' comment.id %}">삭제</a>
                      </div>
                    {% endfor %}
                  </div>
                {% endif %}
                <div>
                  <a href="{% url 'board:comment_create_answer' answer.id %}" class="small">댓글추가....</a>
                </div>
                <!--답변 comment 종료-->
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      <!-- 답변 반복 종료-->

      <!-- 답변 댓글 작성 부분-->
      <div class="mt-3">
        {% include 'form_errors.html' %}
        <form action="{% url 'board:answer_create' question.id %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <textarea name="content" id="content" cols="30" rows="10" class="form-control" {% if not user.is_authenticated %} disabled="disabled" {% endif %}></textarea>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">답변등록</button>
          </div>
        </form>
      </div>
      <!-- 답변 댓글 종료-->
    </div>
  </div>

{% endblock content %}

{% block script %}
  <script>
    // 질문 삭제 버튼 클릭 시 '정말로 삭제하시겠습니까?' =>  확인을 누르면 삭제
    $(function () {
      $(".btn-outline-danger, .delete").on("click", function () {
        if (confirm("정말로 삭제하시겠습니까?")) {
          // data-uri 에 있는 값 가져온 후 location.href 이용해서 이동
          console.log($(this).data("uri"));
          location.href = $(this).data("uri");
        }
      });

      $(".recommend").on("click", function () {
        if (confirm("정말로 추천하시겠습니까?")) {
          // data-uri 에 있는 값 가져온 후 location.href 이용해서 이동
          console.log($(this).data("uri"));
          location.href = $(this).data("uri");
        }
      });

      //목록으로 클릭시 searchForm 보내기
      $(".btn-outline-success").on('click', function () {
        $("#searchForm").submit();
      })

    })
  </script>
{% endblock script %}

myboard/templates/board/question_modify.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <h5 class="border-bottom py-2">
      질문 수정
    </h5>
    {% include 'form_errors.html' %}
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="subject">제목</label>
        <input type="text" name="subject" id="subject" class="form-control" value="{{form.subject.value|default_if_none:''}}">
      </div>
      <div class="form-group">
        <label for="content">내용</label>
        <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{form.content.value|default_if_none:''}}</textarea>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">수정하기</button>
      </div>
    </form>
  </div>
{% endblock content %}